---
- name: show_command
  hosts: lab
  gather_facts: false
  connection: network_cli

  tasks:

#    # Collect all facts from the device
#    - name: Collect all facts from the device
#      ios_facts:
#        gather_subset: all
#
#    # Collect only the config and default facts
#    - name: Collect only the config and default facts
#      ios_facts:
#        gather_subset:
#        - config
#
#    # Do not collect hardware facts
#    - name: Do not collect hardware facts
#      ios_facts:
#        gather_subset:
#        - "!hardware"

    - name: gather_facts
      ios_facts:
        gather_subset:
          - config

      register: config_facts

    # By using the var.ansible_facts.dict_key format we can pull out the data we want from the variable
    # Use the comma to seperate the data if you want more than one value out of the dictionary
    - debug: var=config_facts.ansible_facts.ansible_net_hostname,config_facts.ansible_facts.ansible_net_model,config_facts.ansible_facts.ansible_net_serialnum,config_facts.ansible_facts.ansible_net_version

    - name: DISPLAY VERSION
      debug:
        msg: "The IOS version is: {{ ansible_net_version }}"

    - name: DISPLAY SERIAL NUMBER
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"

    - name: Create dir
      file:
#         path: "/tmp/{{ inventory_hostname }}"
        path: "./facts_output"
        state: directory
        recurse: yes
      delegate_to: 127.0.0.1

    - name: save output to a file
      delegate_to: 127.0.0.1
      copy:
        # copy the value after the debug: var= to the content: "{{ <here> }}"
        content: "{{ config_facts.ansible_facts.ansible_net_hostname,config_facts.ansible_facts.ansible_net_model,config_facts.ansible_facts.ansible_net_serialnum,config_facts.ansible_facts.ansible_net_version }}"
        dest: "./facts_output/facts.txt"
#         dest: "/tmp/{{ inventory_hostname }}/{{ inventory_hostname }}_get_facts.txt"
