---
############ NOT WORKING YET#############
- name: Backup Switch Configuration
  hosts: cisco
  gather_facts: false
  connection: network_cli
  
  tasks:
  ###
    # Get running configuration
    #

    - name: Backup switch (ios)
      ios_config:
        backup: yes
      register: backup_ios_location
      when: ansible_network_os == 'ios'

    - name: Create backup dir
      file:
        path: "/tmp/backups/{{ ansible_net_hostname }}"
        state: directory
        recurse: yes

    - name: Copy backup files into /tmp/backups/ (ios)
      copy:
        src: "{{ backup_ios_location.backup_path }}"
        dest: "/tmp/backups/{{ ansible_net_hostname }}/{{ ansible_net_hostname }}.bck"
      when: ansible_network_os == 'ios'
  
    - debug: var=inventory_hostname
    - debug: var=ansible_hostname
    - debug: var=hostvars
    
