---
- name: Backup Switch Configuration
  hosts: cisco
  gather_facts: false
  connection: network_cli
  
  tasks:
  ###
    # Get running configuration
    #

    - name: Backup switch (ios)
      ios_config:
        backup: yes
      register: backup_ios_location
      when: ansible_network_os == 'ios'

    - name: Create backup dir
      file:
        path: "10.57.213.114/Users/satish.kumar/Desktop/temp/{{ inventory_hostname }}"
        state: directory
        recurse: yes
#       delegate_to: 127.0.0.1

    - name: Copy backup files into /tmp/backups/ (ios)
      copy:
        src: "{{ backup_ios_location.backup_path }}"
        dest: "10.57.213.114/Users/satish.kumar/Desktop/temp/{{ inventory_hostname }}/{{ inventory_hostname }}.bck"
#       delegate_to: 127.0.0.1
    
