---
- name: COLLECT INFORMATION FROM CISCO IOS DEVICES
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
    # Collect all facts from the device
    - ios_facts:
      gather_subset: all

    # Collect only the config and default facts
    - ios_facts:
      gather_subset:
        - config

    # Do not collect hardware facts
    - ios_facts:
      gather_subset:
        - "!hardware"
