---
- hosts: paloalto
  connection: local
  gather_facts: no

  tasks:
  - name: show list of all interfaces
    panos_op:
      ip_address: '{{ hosts }}'
#       username: '{{ username }}'
#       password: '{{ password }}'
      cmd: 'show interfaces all'

