---
- hosts: paloalto
  connection: local
  gather_facts: no

  tasks:
  - name: show list of all interfaces
    panos_op:
      ip_address: '10.57.242.56'
      username: 'ccie'
      password: 'python'
      cmd: 'show interfaces all'

