---
- name: GENERATE MGMT CONFIG FOR LAB DEVICES
  hosts: lab
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/{{ inventory_hostname }}.yml
  roles:
    - mgmt_all_config

- name: GENERATE VLAN CONFIG ACCESS SWITCHES
  hosts: 10.57.242.54 # 4500x
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/{{ inventory_hostname }}.yml
  roles:
    - access_vlans